# Generated by Django 6.0.4 on 2026-04-29 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVariable',
            fields=[
                ('id_tipo_variable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('simbolo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_variable',
            },
        ),
        migrations.CreateModel(
            name='ZonaMonitoreo',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zona_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='DispositivoIot',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=80)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='core.zonamonitoreo')),
            ],
            options={
                'db_table': 'dispositivo_iot',
            },
        ),
    ]
