# Generated by Django 6.0.4 on 2026-04-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estadoambiental_recurso_rol_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBuzzer',
            fields=[
                ('id_estado_buzzer', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('motivo_variacion', models.CharField(blank=True, max_length=255, null=True)),
                ('activado_por', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_alerta', models.ForeignKey(db_column='id_alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alerta')),
                ('id_buzzer', models.ForeignKey(db_column='id_buzzer', on_delete=django.db.models.deletion.CASCADE, to='core.buzzer')),
            ],
            options={
                'db_table': 'estado_buzzer',
            },
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id_respuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_respuesta', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('exitoso', models.BooleanField(default=True)),
                ('respuesta_json', models.JSONField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('id_comando', models.ForeignKey(db_column='id_comando', on_delete=django.db.models.deletion.CASCADE, to='core.comandoremoto')),
            ],
            options={
                'db_table': 'respuesta_comando',
            },
        ),
    ]
