# Generated by Django 6.0.4 on 2026-05-02 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estadobuzzer_respuestacomando'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariohasrol',
            name='usuario_idusuarios',
            field=models.ForeignKey(db_column='usuario_idusuarios', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
